syntax = "proto3";

package iopattern;

option go_package = "linux_tracer/proto;main";

message IOFlags {
    optional uint64 nowait = 1;
    optional uint64 write = 2;
    optional uint64 dsync = 3;
    optional uint64 sync = 4;
    optional uint64 append = 5;
    optional uint64 hiprio = 6;
    optional uint64 atomic = 7;
    optional uint64 doncache = 8;
    optional uint64 nosignal = 9;
    optional uint64 eventfd = 10;
    optional uint64 direct = 11;
    optional uint64 waitq = 12;
    optional uint64 noio = 13;
    optional uint64 alloc_cache = 14;
    optional uint64 aio_rw = 15;
    optional uint64 has_metadata = 16;
}

message IOStats {
    optional uint64 io_count = 1;
    optional uint64 io_size_bytes = 2;
    optional uint64 buffered_io_count = 3;
    optional uint64 buffered_io_size_bytes = 4;
    optional uint64 direct_io_count = 5;
    optional uint64 direct_io_size_bytes = 6;

    IOSizeBuckets io_size_buckets = 7;
    IORangeBuckets io_range_buckets = 8;
}

message IOSizeBuckets {
    optional uint64 BLt4KB = 1;
    optional uint64 B4KB = 2;
    optional uint64 B8KB = 3;
    optional uint64 B16KB = 4;
    optional uint64 B32KB = 5;
    optional uint64 B64KB = 6;
    optional uint64 B128KB = 7;
    optional uint64 B256KB = 8;
    optional uint64 B512KB = 9;
    optional uint64 B1MB = 10;
    optional uint64 B2MB = 11;
    optional uint64 B4MB = 12;
    optional uint64 B8MB = 13;
    optional uint64 BGt8MB = 14;
    optional uint64 BUnaligned = 15;
}

message IORangeBuckets {
    optional uint64 lt_4kb = 1;
    optional uint64 k4_to_k8 = 2;
    optional uint64 k8_to_k16 = 3;
    optional uint64 k16_to_k32 = 4;
    optional uint64 k32_to_k64 = 5;
    optional uint64 k64_to_k128 = 6;
    optional uint64 k128_to_k256 = 7;
    optional uint64 k256_to_k512 = 8;
    optional uint64 k512_to_m1 = 9;
    optional uint64 m1_to_m2 = 10;
    optional uint64 m2_to_m4 = 11;
    optional uint64 m4_to_m8 = 12;
}

message GenericFormat {
    optional string timestamp = 1;
    optional string hostname = 2;
    optional uint32 component = 3;
    optional string tag = 4;
    optional uint32 log_level = 5;
}

message Payload {
    IOStats read_io_stats = 1;
    IOFlags read_io_flags = 2;
    IOStats write_io_stats = 3;
    IOFlags write_io_flags = 4;
}

message StatLog {
    GenericFormat generic_format = 1;
    Payload payload = 2;
}

message StatLogs {
    repeated StatLog stats_log = 1;
}