syntax = "proto3";

message GenericFormat {
    optional string timestamp = 1;
    optional string hostname = 2;
    optional uint32 component = 3;
    optional string tag = 4;
    optional uint32 log_level = 5;
}

message BlkBioQueuePayload {
    optional uint64 read_splits = 6;
    optional uint64 write_splits = 7;

    optional uint64 read_4kb = 8;
    optional uint64 read_8kb = 9;
    optional uint64 read_16kb = 10;
    optional uint64 read_32kb = 11;
    optional uint64 read_64kb = 12;
    optional uint64 read_128kb = 13;
    optional uint64 read_256kb = 14;
    optional uint64 read_512kb = 15;
    optional uint64 read_1mb = 16;
    optional uint64 read_gt_1mb = 17;
    optional uint64 read_other = 18;

    optional uint64 write_4kb = 19;
    optional uint64 write_8kb = 20;
    optional uint64 write_16kb = 21;
    optional uint64 write_32kb = 22;
    optional uint64 write_64kb = 23;
    optional uint64 write_128kb = 24;
    optional uint64 write_256kb = 25;
    optional uint64 write_512kb = 26;
    optional uint64 write_1mb = 27;
    optional uint64 write_gt_1mb = 28;
    optional uint64 write_other = 29;

    optional uint64 read_bios = 30;
    optional uint64 write_bios = 31;
}

message BlkBioQueueEvent {
    GenericFormat generic_format = 1;
    BlkBioQueuePayload payload = 2;
}

message BlkBioQueueEvents {
    repeated BlkBioQueueEvent blk_bio_queue_events = 1;
}
