syntax = "proto3";

message BlockDeviceStat {
    optional string device = 1;

    optional uint64 read_ios = 2;
    optional uint64 reads_merged = 3;
    optional uint64 sectors_read = 4;
    optional uint64 read_time_ms = 5;

    optional uint64 write_ios = 6;
    optional uint64 writes_merged = 7;
    optional uint64 sectors_written = 8;
    optional uint64 write_time_ms = 9;

    optional uint64 in_flight_ios = 10;
    optional uint64 device_busy_time = 11;
    optional uint64 io_time = 12;

    optional uint64 discard_ios = 13;
    optional uint64 discards_merged = 14;
    optional uint64 sectors_discarded = 15;
    optional uint64 discard_time_ms = 16;

    optional uint64 flush_ios = 17;
    optional uint64 flush_time_ms = 18;
}

message GenericFormat {
    optional string timestamp = 1;
    optional string hostname = 2;
    optional uint32 component = 3;
    optional string tag = 4;
    optional uint32 log_level = 5;
}

message BlockStatSample {
    GenericFormat generic_format = 1;
    BlockDeviceStat payload = 2;
}

message BlockDeviceStatLog {
    repeated BlockStatSample block_device_stats = 1;
}
